# Generated by Django 3.0 on 2020-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='pekerjaan',
            field=models.CharField(choices=[('P001', 'PETANI/PEKEBUN'), ('P002', 'PETERNAK'), ('P003', 'NELAYAN/PERIKANAN'), ('P004', 'TRANSPORTASI'), ('P005', 'BURUH HARIAN LEPAS'), ('P006', 'BURUH TANI/PERKEBUNAN'), ('P007', 'BURUH NELAYAN/PERIKANAN'), ('P008', 'BURUH PETERNAKAN'), ('P009', 'PEMBANTU RUMAH TANGGA'), ('P010', 'TUKANG CUKUR'), ('P011', 'TUKANG LISTRIK'), ('P012', 'TUKANG BATU'), ('P013', 'TUKANG KAYU'), ('P014', 'TUKANG SOL SEPATU'), ('P015', 'TUKANG LAS/PANDAI BESI'), ('P016', 'TUKANG JAHIT'), ('P017', 'TUKANG GIGI'), ('P018', 'PENATA RIAS'), ('P019', 'PENATA BUSANA'), ('P020', 'PENATA RAMBUT'), ('P021', 'MEKANIK'), ('P022', 'SENIMAN'), ('P023', 'TABIB'), ('P024', 'PARAJI'), ('P025', 'PERANCANG BUSANA'), ('P026', 'PENTERJEMAH'), ('P027', 'IMAM MESJID'), ('P028', 'PENDETA'), ('P029', 'PASTOR'), ('P030', 'WARTAWAN'), ('P031', 'USTADZ/MUBALIGH'), ('P032', 'JURU MASAK'), ('P033', 'PROMOTOR ACARA'), ('P034', 'DOSEN'), ('P035', 'GURU'), ('P036', 'PENGACARA'), ('P037', 'NOTARIS'), ('P038', 'ARSITEK'), ('P039', 'KONSULTAN'), ('P040', 'DOKTER'), ('P041', 'BIDAN'), ('P042', 'APOTEKER'), ('P043', 'PSIKIATER/PSIKOLOG'), ('P044', 'PENYIAR RADIO'), ('P045', 'PELAUT'), ('P046', 'PENELITI'), ('P047', 'SOPIR'), ('P048', 'PIALANG'), ('P049', 'PARANORMAL'), ('P050', 'PEDAGANG'), ('P051', 'BIARAWATI'), ('P052', 'WIRASWASTA'), ('P053', 'MITRA GOJEK'), ('P054', 'MITRA GRAB'), ('P055', 'MITRA UBER'), ('P056', 'PEKERJA MAGANG'), ('P057', 'SISWA KERJA PRAKTEK'), ('P058', 'TENAGA HONORER (SELAIN PENYELENGGARA NEGARA)'), ('P059', 'NARAPIDANA DALAM PROSES ASIMILASI'), ('P060', 'ATLET'), ('P061', 'ARTIS'), ('P062', 'JURU PARKIR'), ('P063', 'TUKANG PIJAT'), ('P064', 'PEMANDU LAGU'), ('P065', 'PENDAMPING DESA'), ('P066', 'BURUH BONGKAR MUAT/BAGASI'), ('P067', 'RELAWAN TAGANA/RELAWAN BENCANA'), ('P068', 'TUKANG SAMPAH'), ('P069', 'PEMULUNG'), ('P070', 'MARBOT MESJID'), ('P071', 'MITRA GOJEK-GO LIFE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='penghasilan',
            field=models.FloatField(),
        ),
    ]
