# Generated by Django 3.0 on 2020-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0004_auto_20200121_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=50)),
                ('tempat_lhr', models.CharField(max_length=30)),
                ('tgl_lhr', models.DateField()),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='tempat_lhr',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='tgl_lhr',
        ),
    ]
