# Generated by Django 3.0 on 2020-01-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0005_auto_20200122_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='nik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='daftar.DataTK'),
            preserve_default=False,
        ),
    ]
