# Generated by Django 2.2.7 on 2020-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0006_daftar_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatk',
            name='tgl_lhr',
            field=models.IntegerField(max_length=10),
        ),
    ]
