# Generated by Django 2.2.7 on 2020-01-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0007_auto_20200128_2008'),
        ('daftar', '0007_auto_20200128_1538'),
    ]

    operations = [
    ]
