# Generated by Django 2.2.7 on 2020-01-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0009_auto_20200129_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatk',
            name='nik',
            field=models.CharField(max_length=16),
        ),
    ]
